/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.misproyectos.views.Prestamos;

import com.misproyectos.controllers.prestamo.ConfirmarPrestamoController;

import javax.swing.*;

import static com.misproyectos.views.MainWindow.ShowJPanel;

/**
 *
 * @author IK
 */
public class ConfirmarPrestamo extends javax.swing.JPanel {

    /**
     * Creates new form ConfirmarPrestamo
     */
    public ConfirmarPrestamo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new javax.swing.JPanel();
        headerConfirmarPrestamo = new javax.swing.JPanel();
        ConfirmarPrestamoTitle = new javax.swing.JLabel();
        confirmarPrestamoBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaPrestamosTable = new javax.swing.JTable();
        headerListaPrestamos = new javax.swing.JPanel();
        ListaPrestamosTitulo = new javax.swing.JLabel();
        SelectClienteLbl = new javax.swing.JLabel();
        SelectPeriodicidadLbl = new javax.swing.JLabel();
        confirmarLbl = new javax.swing.JLabel();
        DatosPrestamoLbl = new javax.swing.JLabel();
        decoracion1 = new javax.swing.JPanel();
        num1 = new javax.swing.JLabel();
        decoracion3 = new javax.swing.JPanel();
        num3 = new javax.swing.JLabel();
        decoracion2 = new javax.swing.JPanel();
        num2 = new javax.swing.JLabel();
        anteriorConfirmarPrestamoBtn = new javax.swing.JButton();
        decoracion4 = new javax.swing.JPanel();
        num4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        clienteInfoLbl = new javax.swing.JLabel();
        periodicidadInfoLbl = new javax.swing.JLabel();
        importeInfoLbl = new javax.swing.JLabel();
        plazoInfoLbl = new javax.swing.JLabel();
        interesInfoLbl = new javax.swing.JLabel();
        totalPagarLbl = new javax.swing.JLabel();
        noCuotasInfoLbl = new javax.swing.JLabel();
        montoCuotaInfoLbl = new javax.swing.JLabel();
        clienteSelectedLbl = new javax.swing.JLabel();
        plazoSelectedLbl = new javax.swing.JLabel();
        importeSelectedLbl = new javax.swing.JLabel();
        periodicidadSelectedLbl = new javax.swing.JLabel();
        interesSelectedLbl = new javax.swing.JLabel();
        totalPagarSelectedLbl = new javax.swing.JLabel();
        noCuotasSelectedLbl = new javax.swing.JLabel();
        montoCuotaSelectedLbl = new javax.swing.JLabel();

        background1.setBackground(new java.awt.Color(239, 239, 239));
        background1.setForeground(new java.awt.Color(255, 255, 255));

        headerConfirmarPrestamo.setBackground(new java.awt.Color(0, 124, 239));

        ConfirmarPrestamoTitle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ConfirmarPrestamoTitle.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmarPrestamoTitle.setText("Confirmar Prestamo");

        javax.swing.GroupLayout headerConfirmarPrestamoLayout = new javax.swing.GroupLayout(headerConfirmarPrestamo);
        headerConfirmarPrestamo.setLayout(headerConfirmarPrestamoLayout);
        headerConfirmarPrestamoLayout.setHorizontalGroup(
            headerConfirmarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerConfirmarPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ConfirmarPrestamoTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerConfirmarPrestamoLayout.setVerticalGroup(
            headerConfirmarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerConfirmarPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ConfirmarPrestamoTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        confirmarPrestamoBtn.setBackground(new java.awt.Color(0, 124, 239));
        confirmarPrestamoBtn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        confirmarPrestamoBtn.setForeground(new java.awt.Color(255, 255, 255));
        confirmarPrestamoBtn.setText("Confirmar Prestamo");
        confirmarPrestamoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarPrestamoBtnActionPerformed(evt);
            }
        });

        ListaPrestamosTable.setForeground(new java.awt.Color(255, 255, 255));
        ListaPrestamosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Importe", "Plazo", "Periodicidad", "Fecha Inicio", "Saldo Actual", "Estado"
            }
        ));
        ListaPrestamosTable.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(ListaPrestamosTable);

        headerListaPrestamos.setBackground(new java.awt.Color(51, 51, 51));

        ListaPrestamosTitulo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ListaPrestamosTitulo.setForeground(new java.awt.Color(255, 255, 255));
        ListaPrestamosTitulo.setText("Lista de Prestamos");

        javax.swing.GroupLayout headerListaPrestamosLayout = new javax.swing.GroupLayout(headerListaPrestamos);
        headerListaPrestamos.setLayout(headerListaPrestamosLayout);
        headerListaPrestamosLayout.setHorizontalGroup(
            headerListaPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerListaPrestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListaPrestamosTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerListaPrestamosLayout.setVerticalGroup(
            headerListaPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerListaPrestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListaPrestamosTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SelectClienteLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        SelectClienteLbl.setForeground(new java.awt.Color(51, 153, 0));
        SelectClienteLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SelectClienteLbl.setText("Seleccionar Cliente");

        SelectPeriodicidadLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        SelectPeriodicidadLbl.setForeground(new java.awt.Color(51, 153, 0));
        SelectPeriodicidadLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SelectPeriodicidadLbl.setText("Seleccionar Periodicidad");

        confirmarLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        confirmarLbl.setForeground(new java.awt.Color(51, 153, 0));
        confirmarLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirmarLbl.setText("Confirmar");

        DatosPrestamoLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        DatosPrestamoLbl.setForeground(new java.awt.Color(51, 153, 0));
        DatosPrestamoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DatosPrestamoLbl.setText("Datos del Prestamo");

        decoracion1.setBackground(new java.awt.Color(0, 153, 0));

        num1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        num1.setForeground(new java.awt.Color(255, 255, 255));
        num1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        num1.setText("1");

        javax.swing.GroupLayout decoracion1Layout = new javax.swing.GroupLayout(decoracion1);
        decoracion1.setLayout(decoracion1Layout);
        decoracion1Layout.setHorizontalGroup(
            decoracion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, decoracion1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        decoracion1Layout.setVerticalGroup(
            decoracion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decoracion1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, Short.MAX_VALUE)
                .addContainerGap())
        );

        decoracion3.setBackground(new java.awt.Color(0, 153, 0));

        num3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        num3.setForeground(new java.awt.Color(255, 255, 255));
        num3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        num3.setText("3");

        javax.swing.GroupLayout decoracion3Layout = new javax.swing.GroupLayout(decoracion3);
        decoracion3.setLayout(decoracion3Layout);
        decoracion3Layout.setHorizontalGroup(
            decoracion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, decoracion3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        decoracion3Layout.setVerticalGroup(
            decoracion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decoracion3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, Short.MAX_VALUE)
                .addContainerGap())
        );

        decoracion2.setBackground(new java.awt.Color(0, 153, 0));

        num2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        num2.setForeground(new java.awt.Color(255, 255, 255));
        num2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        num2.setText("2");

        javax.swing.GroupLayout decoracion2Layout = new javax.swing.GroupLayout(decoracion2);
        decoracion2.setLayout(decoracion2Layout);
        decoracion2Layout.setHorizontalGroup(
            decoracion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, decoracion2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        decoracion2Layout.setVerticalGroup(
            decoracion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decoracion2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, Short.MAX_VALUE)
                .addContainerGap())
        );

        anteriorConfirmarPrestamoBtn.setBackground(new java.awt.Color(102, 102, 102));
        anteriorConfirmarPrestamoBtn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        anteriorConfirmarPrestamoBtn.setForeground(new java.awt.Color(255, 255, 255));
        anteriorConfirmarPrestamoBtn.setText("Anterior");
        anteriorConfirmarPrestamoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorConfirmarPrestamoBtnActionPerformed(evt);
            }
        });

        decoracion4.setBackground(new java.awt.Color(0, 153, 0));

        num4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        num4.setForeground(new java.awt.Color(255, 255, 255));
        num4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        num4.setText("4");

        javax.swing.GroupLayout decoracion4Layout = new javax.swing.GroupLayout(decoracion4);
        decoracion4.setLayout(decoracion4Layout);
        decoracion4Layout.setHorizontalGroup(
            decoracion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, decoracion4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        decoracion4Layout.setVerticalGroup(
            decoracion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decoracion4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Resumen del Prestamo");

        clienteInfoLbl.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        clienteInfoLbl.setText("Cliente:");

        periodicidadInfoLbl.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        periodicidadInfoLbl.setText("Periodicidad:");

        importeInfoLbl.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        importeInfoLbl.setText("Importe:");

        plazoInfoLbl.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        plazoInfoLbl.setText("Plazo:");

        interesInfoLbl.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        interesInfoLbl.setText("Interes Total:");

        totalPagarLbl.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        totalPagarLbl.setText("Total a Pagar:");

        noCuotasInfoLbl.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        noCuotasInfoLbl.setText("Numero de Cuotas:");

        montoCuotaInfoLbl.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        montoCuotaInfoLbl.setText("Monto por Cuota:");

        clienteSelectedLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        plazoSelectedLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        importeSelectedLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        periodicidadSelectedLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        interesSelectedLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        totalPagarSelectedLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        noCuotasSelectedLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        montoCuotaSelectedLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(553, Short.MAX_VALUE))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(background1Layout.createSequentialGroup()
                                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SelectClienteLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addGroup(background1Layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(decoracion1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(background1Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(SelectPeriodicidadLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                        .addComponent(DatosPrestamoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(59, 59, 59))
                                    .addGroup(background1Layout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addComponent(decoracion2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(decoracion3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(122, 122, 122)))
                                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(confirmarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                                        .addComponent(decoracion4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37))))
                            .addComponent(jScrollPane2)
                            .addComponent(headerListaPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(headerConfirmarPrestamo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(background1Layout.createSequentialGroup()
                                        .addComponent(periodicidadInfoLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(periodicidadSelectedLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                                    .addGroup(background1Layout.createSequentialGroup()
                                        .addComponent(plazoInfoLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(plazoSelectedLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(background1Layout.createSequentialGroup()
                                        .addComponent(importeInfoLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(importeSelectedLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(background1Layout.createSequentialGroup()
                                        .addComponent(clienteInfoLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(clienteSelectedLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                                        .addComponent(montoCuotaInfoLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(montoCuotaSelectedLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                                        .addComponent(noCuotasInfoLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(noCuotasSelectedLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                                        .addComponent(totalPagarLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(totalPagarSelectedLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                                        .addComponent(interesInfoLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(interesSelectedLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                                        .addComponent(anteriorConfirmarPrestamoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(confirmarPrestamoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)))
                        .addGap(14, 14, 14))))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addComponent(decoracion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(confirmarLbl))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addComponent(decoracion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DatosPrestamoLbl))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addComponent(decoracion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SelectPeriodicidadLbl))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addComponent(decoracion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SelectClienteLbl)))
                .addGap(18, 18, 18)
                .addComponent(headerConfirmarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(interesInfoLbl)
                            .addComponent(interesSelectedLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totalPagarLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalPagarSelectedLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(noCuotasInfoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(noCuotasSelectedLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(montoCuotaInfoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(montoCuotaSelectedLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(clienteInfoLbl)
                            .addComponent(clienteSelectedLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(periodicidadInfoLbl)
                            .addComponent(periodicidadSelectedLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(importeInfoLbl)
                            .addComponent(importeSelectedLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(plazoInfoLbl)
                            .addComponent(plazoSelectedLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmarPrestamoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anteriorConfirmarPrestamoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(headerListaPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void anteriorConfirmarPrestamoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorConfirmarPrestamoBtnActionPerformed
        ShowJPanel(new DatosDelPrestamo());
    }//GEN-LAST:event_anteriorConfirmarPrestamoBtnActionPerformed

    private void confirmarPrestamoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarPrestamoBtnActionPerformed

    }//GEN-LAST:event_confirmarPrestamoBtnActionPerformed

    public JButton getConfirmarPrestamoBtn() {
        return confirmarPrestamoBtn;
    }

    public void setClienteSelectedLbl(String clienteSelectedLbl) {
        this.clienteSelectedLbl.setText(clienteSelectedLbl);
    }

    public void setPeriodicidadSelectedLbl(String periodicidadSelectedLbl) {
        this.periodicidadSelectedLbl.setText(periodicidadSelectedLbl);
    }

    public void setImporteSelectedLbl(String importeSelectedLbl) {
        this.importeSelectedLbl.setText(importeSelectedLbl);
    }

    public void setPlazoSelectedLbl(String plazoSelectedLbl) {
        this.plazoSelectedLbl.setText(plazoSelectedLbl);
    }

    public void setInteresSelectedLbl(String interesSelectedLbl) {
        this.interesSelectedLbl.setText(interesSelectedLbl);
    }

    public void setTotalPagarSelectedLbl(String totalPagarSelectedLbl) {
        this.totalPagarSelectedLbl.setText(totalPagarSelectedLbl);
    }

    public void setNoCuotasSelectedLbl(String noCuotasSelectedLbl) {
        this.noCuotasSelectedLbl.setText(noCuotasSelectedLbl);
    }

    public void setMontoCuotaSelectedLbl(String montoCuotaSelectedLbl) {
        this.montoCuotaSelectedLbl.setText(montoCuotaSelectedLbl);
    }

    public void setController(ConfirmarPrestamoController controller){
        this.controller = controller;
        this.controller.initListeners();
        this.controller.autoFillLabels();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConfirmarPrestamoTitle;
    private javax.swing.JLabel DatosPrestamoLbl;
    private javax.swing.JTable ListaPrestamosTable;
    private javax.swing.JLabel ListaPrestamosTitulo;
    private javax.swing.JLabel SelectClienteLbl;
    private javax.swing.JLabel SelectPeriodicidadLbl;
    private javax.swing.JButton anteriorConfirmarPrestamoBtn;
    private javax.swing.JPanel background1;
    private javax.swing.JLabel clienteInfoLbl;
    private javax.swing.JLabel clienteSelectedLbl;
    private javax.swing.JLabel confirmarLbl;
    private javax.swing.JButton confirmarPrestamoBtn;
    private javax.swing.JPanel decoracion1;
    private javax.swing.JPanel decoracion2;
    private javax.swing.JPanel decoracion3;
    private javax.swing.JPanel decoracion4;
    private javax.swing.JPanel headerConfirmarPrestamo;
    private javax.swing.JPanel headerListaPrestamos;
    private javax.swing.JLabel importeInfoLbl;
    private javax.swing.JLabel importeSelectedLbl;
    private javax.swing.JLabel interesInfoLbl;
    private javax.swing.JLabel interesSelectedLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel montoCuotaInfoLbl;
    private javax.swing.JLabel montoCuotaSelectedLbl;
    private javax.swing.JLabel noCuotasInfoLbl;
    private javax.swing.JLabel noCuotasSelectedLbl;
    private javax.swing.JLabel num1;
    private javax.swing.JLabel num2;
    private javax.swing.JLabel num3;
    private javax.swing.JLabel num4;
    private javax.swing.JLabel periodicidadInfoLbl;
    private javax.swing.JLabel periodicidadSelectedLbl;
    private javax.swing.JLabel plazoInfoLbl;
    private javax.swing.JLabel plazoSelectedLbl;
    private javax.swing.JLabel totalPagarLbl;
    private javax.swing.JLabel totalPagarSelectedLbl;
    private ConfirmarPrestamoController controller;
    // End of variables declaration//GEN-END:variables
}
