/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.misproyectos.views.Prestamos;

import com.misproyectos.controllers.prestamo.ConfirmarPrestamoController;
import com.misproyectos.exceptions.ValidacionException;
import com.misproyectos.repositories.PeriodicidadesRepository;
import com.misproyectos.service.PeriodicidadService;
import com.misproyectos.service.PrestamoService;

import javax.swing.*;
import java.math.BigDecimal;
import java.sql.SQLException;

import static com.misproyectos.views.MainWindow.ShowJPanel;

/**
 *
 * @author IK
 */
public class DatosDelPrestamo extends javax.swing.JPanel {

    /**
     * Creates new form AsignarPrestamos
     */
    public DatosDelPrestamo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new javax.swing.JPanel();
        headerDatosPrestamo = new javax.swing.JPanel();
        DatosPrestamoTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ImportePrestamoLbl = new javax.swing.JLabel();
        PlazoDiasLbl = new javax.swing.JLabel();
        SiguienteBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaPrestamosTable = new javax.swing.JTable();
        headerListaPrestamos = new javax.swing.JPanel();
        ListaPrestamosTitulo = new javax.swing.JLabel();
        PlazoEntreLbl = new javax.swing.JLabel();
        ImporteMayorIgualLbl = new javax.swing.JLabel();
        PlazoDiasSpinner = new javax.swing.JSpinner();
        ImportePrestamoSpinner = new javax.swing.JSpinner();
        SelectClienteLbl = new javax.swing.JLabel();
        SelectPeriodicidadLbl = new javax.swing.JLabel();
        confirmarLbl = new javax.swing.JLabel();
        DatosPrestamoLbl = new javax.swing.JLabel();
        decoracion1 = new javax.swing.JPanel();
        num1 = new javax.swing.JLabel();
        num4 = new javax.swing.JLabel();
        decoracion3 = new javax.swing.JPanel();
        num3 = new javax.swing.JLabel();
        decoracion2 = new javax.swing.JPanel();
        num2 = new javax.swing.JLabel();
        AnteriorBtn = new javax.swing.JButton();

        background1.setBackground(new java.awt.Color(239, 239, 239));
        background1.setForeground(new java.awt.Color(255, 255, 255));

        headerDatosPrestamo.setBackground(new java.awt.Color(0, 124, 239));

        DatosPrestamoTitle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DatosPrestamoTitle.setForeground(new java.awt.Color(255, 255, 255));
        DatosPrestamoTitle.setText("Datos del Prestamo");

        javax.swing.GroupLayout headerDatosPrestamoLayout = new javax.swing.GroupLayout(headerDatosPrestamo);
        headerDatosPrestamo.setLayout(headerDatosPrestamoLayout);
        headerDatosPrestamoLayout.setHorizontalGroup(
                headerDatosPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerDatosPrestamoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(DatosPrestamoTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerDatosPrestamoLayout.setVerticalGroup(
                headerDatosPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerDatosPrestamoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(DatosPrestamoTitle)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));

        ImportePrestamoLbl.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        ImportePrestamoLbl.setText("Importe del Prestamo*");

        PlazoDiasLbl.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        PlazoDiasLbl.setText("Plazo en Dias*");

        SiguienteBtn.setBackground(new java.awt.Color(0, 124, 239));
        SiguienteBtn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        SiguienteBtn.setForeground(new java.awt.Color(255, 255, 255));
        SiguienteBtn.setText("Siguiente");
        SiguienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteBtnActionPerformed(evt);
            }
        });

        ListaPrestamosTable.setForeground(new java.awt.Color(255, 255, 255));
        ListaPrestamosTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "Cliente", "Importe", "Plazo", "Periodicidad", "Fecha Inicio", "Saldo Actual", "Estado"
                }
        ));
        ListaPrestamosTable.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(ListaPrestamosTable);

        headerListaPrestamos.setBackground(new java.awt.Color(51, 51, 51));

        ListaPrestamosTitulo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ListaPrestamosTitulo.setForeground(new java.awt.Color(255, 255, 255));
        ListaPrestamosTitulo.setText("Lista de Prestamos");

        javax.swing.GroupLayout headerListaPrestamosLayout = new javax.swing.GroupLayout(headerListaPrestamos);
        headerListaPrestamos.setLayout(headerListaPrestamosLayout);
        headerListaPrestamosLayout.setHorizontalGroup(
                headerListaPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerListaPrestamosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ListaPrestamosTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerListaPrestamosLayout.setVerticalGroup(
                headerListaPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerListaPrestamosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ListaPrestamosTitulo)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PlazoEntreLbl.setText("El plazo debe de estar entre 7 y 365 dias");

        ImporteMayorIgualLbl.setText("El importe debe ser mayor o igual a $1,000");

        SelectClienteLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        SelectClienteLbl.setForeground(new java.awt.Color(51, 153, 0));
        SelectClienteLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SelectClienteLbl.setText("Seleccionar Cliente");

        SelectPeriodicidadLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        SelectPeriodicidadLbl.setForeground(new java.awt.Color(51, 153, 0));
        SelectPeriodicidadLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SelectPeriodicidadLbl.setText("Seleccionar Periodicidad");

        confirmarLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        confirmarLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirmarLbl.setText("Confirmar");

        DatosPrestamoLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        DatosPrestamoLbl.setForeground(new java.awt.Color(51, 153, 0));
        DatosPrestamoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DatosPrestamoLbl.setText("Datos del Prestamo");

        decoracion1.setBackground(new java.awt.Color(0, 153, 0));

        num1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        num1.setForeground(new java.awt.Color(255, 255, 255));
        num1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        num1.setText("1");

        javax.swing.GroupLayout decoracion1Layout = new javax.swing.GroupLayout(decoracion1);
        decoracion1.setLayout(decoracion1Layout);
        decoracion1Layout.setHorizontalGroup(
                decoracion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, decoracion1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109))
        );
        decoracion1Layout.setVerticalGroup(
                decoracion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(decoracion1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, Short.MAX_VALUE)
                                .addContainerGap())
        );

        num4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        num4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        num4.setText("4");

        decoracion3.setBackground(new java.awt.Color(0, 153, 0));

        num3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        num3.setForeground(new java.awt.Color(255, 255, 255));
        num3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        num3.setText("3");

        javax.swing.GroupLayout decoracion3Layout = new javax.swing.GroupLayout(decoracion3);
        decoracion3.setLayout(decoracion3Layout);
        decoracion3Layout.setHorizontalGroup(
                decoracion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, decoracion3Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109))
        );
        decoracion3Layout.setVerticalGroup(
                decoracion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(decoracion3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, Short.MAX_VALUE)
                                .addContainerGap())
        );

        decoracion2.setBackground(new java.awt.Color(0, 153, 0));

        num2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        num2.setForeground(new java.awt.Color(255, 255, 255));
        num2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        num2.setText("2");

        javax.swing.GroupLayout decoracion2Layout = new javax.swing.GroupLayout(decoracion2);
        decoracion2.setLayout(decoracion2Layout);
        decoracion2Layout.setHorizontalGroup(
                decoracion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, decoracion2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109))
        );
        decoracion2Layout.setVerticalGroup(
                decoracion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(decoracion2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, Short.MAX_VALUE)
                                .addContainerGap())
        );

        AnteriorBtn.setBackground(new java.awt.Color(102, 102, 102));
        AnteriorBtn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        AnteriorBtn.setForeground(new java.awt.Color(255, 255, 255));
        AnteriorBtn.setText("Anterior");
        AnteriorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnteriorBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
                background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(background1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(background1Layout.createSequentialGroup()
                                                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(background1Layout.createSequentialGroup()
                                                                .addComponent(SelectClienteLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(background1Layout.createSequentialGroup()
                                                                .addGap(45, 45, 45)
                                                                .addComponent(decoracion1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(background1Layout.createSequentialGroup()
                                                                .addGap(22, 22, 22)
                                                                .addComponent(SelectPeriodicidadLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(DatosPrestamoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(59, 59, 59))
                                                        .addGroup(background1Layout.createSequentialGroup()
                                                                .addGap(95, 95, 95)
                                                                .addComponent(decoracion2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(decoracion3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(122, 122, 122)))
                                                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(num4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(confirmarLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                                        .addComponent(jScrollPane2)
                                        .addComponent(headerListaPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(headerDatosPrestamo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                                                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ImporteMayorIgualLbl)
                                                        .addComponent(ImportePrestamoLbl)
                                                        .addComponent(ImportePrestamoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(65, 65, 65)
                                                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                                                                .addComponent(AnteriorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(SiguienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(PlazoEntreLbl)
                                                                .addComponent(PlazoDiasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(PlazoDiasLbl)))
                                                .addGap(33, 33, 33)))
                                .addGap(14, 14, 14))
        );
        background1Layout.setVerticalGroup(
                background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(background1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(background1Layout.createSequentialGroup()
                                                .addComponent(num4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(confirmarLbl))
                                        .addGroup(background1Layout.createSequentialGroup()
                                                .addComponent(decoracion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(DatosPrestamoLbl))
                                        .addGroup(background1Layout.createSequentialGroup()
                                                .addComponent(decoracion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(SelectPeriodicidadLbl))
                                        .addGroup(background1Layout.createSequentialGroup()
                                                .addComponent(decoracion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(SelectClienteLbl)))
                                .addGap(18, 18, 18)
                                .addComponent(headerDatosPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(background1Layout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addComponent(ImportePrestamoLbl)
                                                .addGap(12, 12, 12)
                                                .addComponent(ImportePrestamoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(ImporteMayorIgualLbl))
                                        .addGroup(background1Layout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addComponent(PlazoDiasLbl)
                                                .addGap(9, 9, 9)
                                                .addComponent(PlazoDiasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(PlazoEntreLbl)
                                                .addGap(18, 18, 18)
                                                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(SiguienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(AnteriorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(background1Layout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(35, 35, 35)
                                .addComponent(headerListaPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AnteriorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnteriorBtnActionPerformed
        ShowJPanel(new SeleccionarPeriodicidad());
    }//GEN-LAST:event_AnteriorBtnActionPerformed

    private void SiguienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteBtnActionPerformed
        ConfirmarPrestamo confirmarPrestamoView = new ConfirmarPrestamo();
        PrestamoService servicePrestamo = new PrestamoService();
        PeriodicidadService periodicidadService = new PeriodicidadService(
                new PeriodicidadesRepository()
        );
        ConfirmarPrestamoController controller = new ConfirmarPrestamoController(
                confirmarPrestamoView,
                this,
                servicePrestamo,
                periodicidadService
        );
        try {
            confirmarPrestamoView.setController(controller);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        } catch (ValidacionException e) {
            throw new RuntimeException(e);
        }
        if (validateAllSpinners()) {
            ShowJPanel(confirmarPrestamoView);
        }
    }//GEN-LAST:event_SiguienteBtnActionPerformed

    public BigDecimal getImporteSpinner() {
        Object valor = ImportePrestamoSpinner.getValue();
        return new BigDecimal(valor.toString());
    }

    public BigDecimal getPlazoSpinner() {
        Object valor = PlazoDiasSpinner.getValue();
        return new BigDecimal(valor.toString());
    }

    public boolean validateAllSpinners() {
        try {
            validateImporteSpinner();
            validatePlazoSpinner();
            return true;
        } catch (ValidacionException e) {
            mostrarMensaje("Error de validación: " + e.getMessage());
            return false;
        }
    }

    private boolean validateImporteSpinner() throws ValidacionException {
        BigDecimal importe = getImporteSpinner();

        if (importe == null) {
            throw new ValidacionException("El valor no puede ser null");
        }
        if (importe.compareTo(BigDecimal.ZERO) <= 0) {
            throw new ValidacionException("El importe no puede ser menor que cero");
        }
        if (importe.scale() > 2) {
            throw new ValidacionException("El importe tiene mas de 2 decimales");
        }
        if (importe.compareTo(new BigDecimal("1000000")) > 0) {
            throw new ValidacionException("El importe es demasiado alto");
        }

        return true;
    }

    private boolean validatePlazoSpinner() throws ValidacionException {
        BigDecimal plazo = getPlazoSpinner();

        if (plazo == null) {
            throw new ValidacionException("El valor no puede ser null");
        }
        if (plazo.compareTo(BigDecimal.ZERO) <= 0) {
            throw new ValidacionException("El plazo no puede ser menor que cero");
        }
        if (plazo.scale() > 2) {
            throw new ValidacionException("El importe tiene mas de 2 decimales");
        }
        if (plazo.compareTo(new BigDecimal("1000000")) > 0) {
            throw new ValidacionException("El importe es demasiado alto");
        }

        return true;
    }

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

//    public String getImporteSpinner() {
//        Object valor = ImportePrestamoSpinner.getValue();
//        return valor.toString();
//    }
//
//    public String getPlazoSpinner() {
//        Object valor = PlazoDiasSpinner.getValue();
//        return valor.toString();
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnteriorBtn;
    private javax.swing.JLabel DatosPrestamoLbl;
    private javax.swing.JLabel DatosPrestamoTitle;
    private javax.swing.JLabel ImporteMayorIgualLbl;
    private javax.swing.JLabel ImportePrestamoLbl;
    private javax.swing.JSpinner ImportePrestamoSpinner;
    private javax.swing.JTable ListaPrestamosTable;
    private javax.swing.JLabel ListaPrestamosTitulo;
    private javax.swing.JLabel PlazoDiasLbl;
    private javax.swing.JSpinner PlazoDiasSpinner;
    private javax.swing.JLabel PlazoEntreLbl;
    private javax.swing.JLabel SelectClienteLbl;
    private javax.swing.JLabel SelectPeriodicidadLbl;
    private javax.swing.JButton SiguienteBtn;
    private javax.swing.JPanel background1;
    private javax.swing.JLabel confirmarLbl;
    private javax.swing.JPanel decoracion1;
    private javax.swing.JPanel decoracion2;
    private javax.swing.JPanel decoracion3;
    private javax.swing.JPanel header4;
    private javax.swing.JPanel header5;
    private javax.swing.JPanel headerDatosPrestamo;
    private javax.swing.JPanel headerListaPrestamos;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel num1;
    private javax.swing.JLabel num2;
    private javax.swing.JLabel num3;
    private javax.swing.JLabel num4;
    private javax.swing.JLabel title7;
    private javax.swing.JLabel title8;
    // End of variables declaration//GEN-END:variables
}
