/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.misproyectos.views.Prestamos;

import com.misproyectos.controllers.prestamo.SeleccionarClienteController;
import com.misproyectos.models.PrestamoComboItem;

import javax.swing.*;

import static com.misproyectos.views.MainWindow.ShowJPanel;

/**
 *
 * @author IK
 */
public class SeleccionarCliente extends javax.swing.JPanel {

    /**
     * Creates new form SeleccionarCliente
     */
    public SeleccionarCliente() {
        initComponents();
        cargarClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new javax.swing.JPanel();
        headerSelectCliente = new javax.swing.JPanel();
        SelectClienteTitle = new javax.swing.JLabel();
        ClienteLbl = new javax.swing.JLabel();
        SiguienteSelectClienteBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaPrestamosTable = new javax.swing.JTable();
        headerListaPrestamos = new javax.swing.JPanel();
        ListaPrestamosTitulo = new javax.swing.JLabel();
        confirmarLbl = new javax.swing.JLabel();
        decoracion1 = new javax.swing.JPanel();
        num1 = new javax.swing.JLabel();
        num4 = new javax.swing.JLabel();
        num5 = new javax.swing.JLabel();
        SelectClienteLbl = new javax.swing.JLabel();
        SelectPeriodicidadLbl = new javax.swing.JLabel();
        DatosPrestamoLbl = new javax.swing.JLabel();
        num6 = new javax.swing.JLabel();
        SelectClienteComboBox = new javax.swing.JComboBox<>();

        background1.setBackground(new java.awt.Color(239, 239, 239));
        background1.setForeground(new java.awt.Color(255, 255, 255));

        headerSelectCliente.setBackground(new java.awt.Color(0, 124, 239));

        SelectClienteTitle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        SelectClienteTitle.setForeground(new java.awt.Color(255, 255, 255));
        SelectClienteTitle.setText("Seleccionar Cliente");

        javax.swing.GroupLayout headerSelectClienteLayout = new javax.swing.GroupLayout(headerSelectCliente);
        headerSelectCliente.setLayout(headerSelectClienteLayout);
        headerSelectClienteLayout.setHorizontalGroup(
            headerSelectClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerSelectClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SelectClienteTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerSelectClienteLayout.setVerticalGroup(
            headerSelectClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerSelectClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SelectClienteTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ClienteLbl.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        ClienteLbl.setText("Cliente*");

        SiguienteSelectClienteBtn.setBackground(new java.awt.Color(0, 124, 239));
        SiguienteSelectClienteBtn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        SiguienteSelectClienteBtn.setForeground(new java.awt.Color(255, 255, 255));
        SiguienteSelectClienteBtn.setText("Siguiente");
        SiguienteSelectClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteSelectClienteBtnActionPerformed(evt);
            }
        });

        ListaPrestamosTable.setForeground(new java.awt.Color(255, 255, 255));
        ListaPrestamosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Importe", "Plazo", "Periodicidad", "Fecha Inicio", "Saldo Actual", "Estado"
            }
        ));
        ListaPrestamosTable.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(ListaPrestamosTable);

        headerListaPrestamos.setBackground(new java.awt.Color(51, 51, 51));

        ListaPrestamosTitulo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ListaPrestamosTitulo.setForeground(new java.awt.Color(255, 255, 255));
        ListaPrestamosTitulo.setText("Lista de Prestamos");

        javax.swing.GroupLayout headerListaPrestamosLayout = new javax.swing.GroupLayout(headerListaPrestamos);
        headerListaPrestamos.setLayout(headerListaPrestamosLayout);
        headerListaPrestamosLayout.setHorizontalGroup(
            headerListaPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerListaPrestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListaPrestamosTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerListaPrestamosLayout.setVerticalGroup(
            headerListaPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerListaPrestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListaPrestamosTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        confirmarLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        confirmarLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirmarLbl.setText("Confirmar");

        decoracion1.setBackground(new java.awt.Color(0, 153, 0));

        num1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        num1.setForeground(new java.awt.Color(255, 255, 255));
        num1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        num1.setText("1");

        javax.swing.GroupLayout decoracion1Layout = new javax.swing.GroupLayout(decoracion1);
        decoracion1.setLayout(decoracion1Layout);
        decoracion1Layout.setHorizontalGroup(
            decoracion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, decoracion1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        decoracion1Layout.setVerticalGroup(
            decoracion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decoracion1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, Short.MAX_VALUE)
                .addContainerGap())
        );

        num4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        num4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        num4.setText("4");

        num5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        num5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        num5.setText("2");

        SelectClienteLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        SelectClienteLbl.setForeground(new java.awt.Color(51, 153, 0));
        SelectClienteLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SelectClienteLbl.setText("Seleccionar Cliente");

        SelectPeriodicidadLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        SelectPeriodicidadLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SelectPeriodicidadLbl.setText("Seleccionar Periodicidad");

        DatosPrestamoLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        DatosPrestamoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DatosPrestamoLbl.setText("Datos del Prestamo");

        num6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        num6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        num6.setText("3");

        SelectClienteComboBox.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        SelectClienteComboBox = new JComboBox<PrestamoComboItem>();
        SelectClienteComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectClienteComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(background1Layout.createSequentialGroup()
                                .addComponent(SelectClienteLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(SelectPeriodicidadLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                .addComponent(DatosPrestamoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68))
                            .addGroup(background1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(decoracion1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(164, 164, 164)
                                .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(128, 128, 128)))
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(num4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(confirmarLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2)
                    .addComponent(headerListaPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(headerSelectCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ClienteLbl)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SelectClienteComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(background1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(SiguienteSelectClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)))
                .addGap(14, 14, 14))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addComponent(num4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(confirmarLbl))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(decoracion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DatosPrestamoLbl)
                            .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SelectClienteLbl)
                                .addComponent(SelectPeriodicidadLbl)))))
                .addGap(18, 18, 18)
                .addComponent(headerSelectCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(ClienteLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(SelectClienteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(SiguienteSelectClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(headerListaPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SiguienteSelectClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteSelectClienteBtnActionPerformed
        ShowJPanel(new SeleccionarPeriodicidad());
    }//GEN-LAST:event_SiguienteSelectClienteBtnActionPerformed

    private void SelectClienteComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectClienteComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectClienteComboBoxActionPerformed

    private void cargarClientes(){
        SeleccionarClienteController controller = new SeleccionarClienteController(this);
        controller.loadClientesJBox();
    }

    public JComboBox<PrestamoComboItem> getJComboBoxCliente(){
        return SelectClienteComboBox;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClienteLbl;
    private javax.swing.JLabel DatosPrestamoLbl;
    private javax.swing.JTable ListaPrestamosTable;
    private javax.swing.JLabel ListaPrestamosTitulo;
    private javax.swing.JComboBox<PrestamoComboItem> SelectClienteComboBox = new JComboBox<PrestamoComboItem>();
    private javax.swing.JLabel SelectClienteLbl;
    private javax.swing.JLabel SelectClienteTitle;
    private javax.swing.JLabel SelectPeriodicidadLbl;
    private javax.swing.JButton SiguienteSelectClienteBtn;
    private javax.swing.JPanel background1;
    private javax.swing.JLabel confirmarLbl;
    private javax.swing.JPanel decoracion1;
    private javax.swing.JPanel headerListaPrestamos;
    private javax.swing.JPanel headerSelectCliente;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel num1;
    private javax.swing.JLabel num4;
    private javax.swing.JLabel num5;
    private javax.swing.JLabel num6;
    // End of variables declaration//GEN-END:variables
}
