/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.misproyectos.views.Prestamos;

import com.misproyectos.models.Periodicidad;

import static com.misproyectos.views.MainWindow.ShowJPanel;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author IK
 */
public class SeleccionarPeriodicidad extends javax.swing.JPanel {

    /**
     * Creates new form SeleccionarPeriodicidad
     */
    public SeleccionarPeriodicidad() {
        initComponents();
        cargarPeriodicidades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new javax.swing.JPanel();
        headerSeleccionarPeriodicidad = new javax.swing.JPanel();
        SeleccionarPeriodicidadTitle = new javax.swing.JLabel();
        PeriodicidadPagoLbl = new javax.swing.JLabel();
        SiguienteSeleccionarPeriodicidadBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaPrestamosTable = new javax.swing.JTable();
        headerListaPrestamos = new javax.swing.JPanel();
        ListaPrestamosTitulo = new javax.swing.JLabel();
        confirmarLbl = new javax.swing.JLabel();
        decoracion1 = new javax.swing.JPanel();
        num1 = new javax.swing.JLabel();
        num4 = new javax.swing.JLabel();
        SelectClienteLbl = new javax.swing.JLabel();
        DatosPrestamoLbl = new javax.swing.JLabel();
        num6 = new javax.swing.JLabel();
        SeleccionarPeriodicidadComboBox = new javax.swing.JComboBox<>();
        decoracion2 = new javax.swing.JPanel();
        num2 = new javax.swing.JLabel();
        SelectPeriodicidadLbl = new javax.swing.JLabel();
        AnteriorSeleccionarPeriodicidadBtn = new javax.swing.JButton();

        background1.setBackground(new java.awt.Color(239, 239, 239));
        background1.setForeground(new java.awt.Color(255, 255, 255));

        headerSeleccionarPeriodicidad.setBackground(new java.awt.Color(0, 124, 239));

        SeleccionarPeriodicidadTitle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        SeleccionarPeriodicidadTitle.setForeground(new java.awt.Color(255, 255, 255));
        SeleccionarPeriodicidadTitle.setText("Seleccionar Periodicidad");

        javax.swing.GroupLayout headerSeleccionarPeriodicidadLayout = new javax.swing.GroupLayout(headerSeleccionarPeriodicidad);
        headerSeleccionarPeriodicidad.setLayout(headerSeleccionarPeriodicidadLayout);
        headerSeleccionarPeriodicidadLayout.setHorizontalGroup(
            headerSeleccionarPeriodicidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerSeleccionarPeriodicidadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SeleccionarPeriodicidadTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerSeleccionarPeriodicidadLayout.setVerticalGroup(
            headerSeleccionarPeriodicidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerSeleccionarPeriodicidadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SeleccionarPeriodicidadTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PeriodicidadPagoLbl.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        PeriodicidadPagoLbl.setText("Periodicidad de Pago*");

        SiguienteSeleccionarPeriodicidadBtn.setBackground(new java.awt.Color(0, 124, 239));
        SiguienteSeleccionarPeriodicidadBtn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        SiguienteSeleccionarPeriodicidadBtn.setForeground(new java.awt.Color(255, 255, 255));
        SiguienteSeleccionarPeriodicidadBtn.setText("Siguiente");
        SiguienteSeleccionarPeriodicidadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteSeleccionarPeriodicidadBtnActionPerformed(evt);
            }
        });

        ListaPrestamosTable.setForeground(new java.awt.Color(255, 255, 255));
        ListaPrestamosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Importe", "Plazo", "Periodicidad", "Fecha Inicio", "Saldo Actual", "Estado"
            }
        ));
        ListaPrestamosTable.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(ListaPrestamosTable);

        headerListaPrestamos.setBackground(new java.awt.Color(51, 51, 51));

        ListaPrestamosTitulo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ListaPrestamosTitulo.setForeground(new java.awt.Color(255, 255, 255));
        ListaPrestamosTitulo.setText("Lista de Prestamos");

        javax.swing.GroupLayout headerListaPrestamosLayout = new javax.swing.GroupLayout(headerListaPrestamos);
        headerListaPrestamos.setLayout(headerListaPrestamosLayout);
        headerListaPrestamosLayout.setHorizontalGroup(
            headerListaPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerListaPrestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListaPrestamosTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerListaPrestamosLayout.setVerticalGroup(
            headerListaPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerListaPrestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListaPrestamosTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        confirmarLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        confirmarLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirmarLbl.setText("Confirmar");

        decoracion1.setBackground(new java.awt.Color(0, 153, 0));

        num1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        num1.setForeground(new java.awt.Color(255, 255, 255));
        num1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        num1.setText("1");

        javax.swing.GroupLayout decoracion1Layout = new javax.swing.GroupLayout(decoracion1);
        decoracion1.setLayout(decoracion1Layout);
        decoracion1Layout.setHorizontalGroup(
            decoracion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, decoracion1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        decoracion1Layout.setVerticalGroup(
            decoracion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decoracion1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, Short.MAX_VALUE)
                .addContainerGap())
        );

        num4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        num4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        num4.setText("4");

        SelectClienteLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        SelectClienteLbl.setForeground(new java.awt.Color(51, 153, 0));
        SelectClienteLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SelectClienteLbl.setText("Seleccionar Cliente");

        DatosPrestamoLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        DatosPrestamoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DatosPrestamoLbl.setText("Datos del Prestamo");

        num6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        num6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        num6.setText("3");

        SeleccionarPeriodicidadComboBox.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        SeleccionarPeriodicidadComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una Periodicidad", "Periodicidad 1", " " }));
        SeleccionarPeriodicidadComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarPeriodicidadComboBoxActionPerformed(evt);
            }
        });

        decoracion2.setBackground(new java.awt.Color(0, 153, 0));

        num2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        num2.setForeground(new java.awt.Color(255, 255, 255));
        num2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        num2.setText("2");

        javax.swing.GroupLayout decoracion2Layout = new javax.swing.GroupLayout(decoracion2);
        decoracion2.setLayout(decoracion2Layout);
        decoracion2Layout.setHorizontalGroup(
            decoracion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, decoracion2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        decoracion2Layout.setVerticalGroup(
            decoracion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decoracion2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, Short.MAX_VALUE)
                .addContainerGap())
        );

        SelectPeriodicidadLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        SelectPeriodicidadLbl.setForeground(new java.awt.Color(51, 153, 0));
        SelectPeriodicidadLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SelectPeriodicidadLbl.setText("Seleccionar Periodicidad");

        AnteriorSeleccionarPeriodicidadBtn.setBackground(new java.awt.Color(102, 102, 102));
        AnteriorSeleccionarPeriodicidadBtn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        AnteriorSeleccionarPeriodicidadBtn.setForeground(new java.awt.Color(255, 255, 255));
        AnteriorSeleccionarPeriodicidadBtn.setText("Anterior");
        AnteriorSeleccionarPeriodicidadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnteriorSeleccionarPeriodicidadBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SelectClienteLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(background1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(decoracion1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(background1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(SelectPeriodicidadLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(background1Layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(decoracion2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                                .addComponent(DatosPrestamoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                                .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(128, 128, 128)))
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(num4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(confirmarLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2)
                    .addComponent(headerListaPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(headerSeleccionarPeriodicidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addComponent(PeriodicidadPagoLbl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SeleccionarPeriodicidadComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(background1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(AnteriorSeleccionarPeriodicidadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(SiguienteSeleccionarPeriodicidadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)))
                .addGap(14, 14, 14))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addComponent(num4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(confirmarLbl))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(decoracion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(decoracion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DatosPrestamoLbl)
                            .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SelectClienteLbl)
                                .addComponent(SelectPeriodicidadLbl)))))
                .addGap(18, 18, 18)
                .addComponent(headerSeleccionarPeriodicidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(PeriodicidadPagoLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(SeleccionarPeriodicidadComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiguienteSeleccionarPeriodicidadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnteriorSeleccionarPeriodicidadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(headerListaPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SiguienteSeleccionarPeriodicidadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteSeleccionarPeriodicidadBtnActionPerformed
        ShowJPanel(new DatosDelPrestamo());
        String seleccion = (String) this.SeleccionarPeriodicidadComboBox.getSelectedItem();
        System.out.println("Seleccionado: " + seleccion);
    }//GEN-LAST:event_SiguienteSeleccionarPeriodicidadBtnActionPerformed

    private void SeleccionarPeriodicidadComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarPeriodicidadComboBoxActionPerformed
        
    }//GEN-LAST:event_SeleccionarPeriodicidadComboBoxActionPerformed

    private void AnteriorSeleccionarPeriodicidadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnteriorSeleccionarPeriodicidadBtnActionPerformed
        ShowJPanel(new SeleccionarCliente());
    }//GEN-LAST:event_AnteriorSeleccionarPeriodicidadBtnActionPerformed


    private void cargarPeriodicidades(){
//        List<String> periodicidades = new ArrayList<>();
//
//        periodicidades.add("quincenal");
//        periodicidades.add("mensual");
//        periodicidades.add("semanal");
//
//        this.SeleccionarPeriodicidadComboBox.removeAllItems();
//
//        for (String nombre : periodicidades){
//            this.SeleccionarPeriodicidadComboBox.addItem(nombre);
//        }

        List<Periodicidad> list = new ArrayList<>();

        Periodicidad p1 = new Periodicidad();
        p1.setNombrePeriodicidad("quincenal");

        Periodicidad p2 = new Periodicidad();
        p2.setNombrePeriodicidad("semanal");

        Periodicidad p3 = new Periodicidad();
        p3.setNombrePeriodicidad("mensual");

        list.add(p1);
        list.add(p2);
        list.add(p3);

        this.SeleccionarPeriodicidadComboBox.removeAllItems();

        for (Periodicidad p : list){
            //System.out.println(p.getNombrePeriodicidad());
            this.SeleccionarPeriodicidadComboBox.addItem(p.getNombrePeriodicidad());
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnteriorSeleccionarPeriodicidadBtn;
    private javax.swing.JLabel DatosPrestamoLbl;
    private javax.swing.JTable ListaPrestamosTable;
    private javax.swing.JLabel ListaPrestamosTitulo;
    private javax.swing.JLabel PeriodicidadPagoLbl;
    private javax.swing.JComboBox<String> SeleccionarPeriodicidadComboBox;
    private javax.swing.JLabel SeleccionarPeriodicidadTitle;
    private javax.swing.JLabel SelectClienteLbl;
    private javax.swing.JLabel SelectPeriodicidadLbl;
    private javax.swing.JButton SiguienteSeleccionarPeriodicidadBtn;
    private javax.swing.JPanel background1;
    private javax.swing.JLabel confirmarLbl;
    private javax.swing.JPanel decoracion1;
    private javax.swing.JPanel decoracion2;
    private javax.swing.JPanel headerListaPrestamos;
    private javax.swing.JPanel headerSeleccionarPeriodicidad;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel num1;
    private javax.swing.JLabel num2;
    private javax.swing.JLabel num4;
    private javax.swing.JLabel num6;
    // End of variables declaration//GEN-END:variables
}
