/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.misproyectos.views.RegistrosDePagos;

/**
 *
 * @author IK
 */
public class RealizarPago extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RealizarPago.class.getName());

    /**
     * Creates new form RealizarPago
     */
    public RealizarPago(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        titleRealizarPagos = new javax.swing.JLabel();
        LblCliente = new javax.swing.JLabel();
        nombreClienteInput = new javax.swing.JTextField();
        LblSaldoPendiente = new javax.swing.JLabel();
        SaldoPendienteInput = new javax.swing.JTextField();
        LblCantidadPagar = new javax.swing.JLabel();
        CantidadPagarInput = new javax.swing.JTextField();
        saveBtnRealizarPagos = new javax.swing.JButton();
        CancelBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        background1.setBackground(new java.awt.Color(239, 239, 239));
        background1.setForeground(new java.awt.Color(255, 255, 255));

        header.setBackground(new java.awt.Color(0, 124, 239));

        titleRealizarPagos.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        titleRealizarPagos.setForeground(new java.awt.Color(255, 255, 255));
        titleRealizarPagos.setText("Realizar Pagos");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleRealizarPagos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleRealizarPagos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LblCliente.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        LblCliente.setText("Cliente");

        nombreClienteInput.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        nombreClienteInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nombreClienteInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreClienteInputActionPerformed(evt);
            }
        });

        LblSaldoPendiente.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        LblSaldoPendiente.setText("Saldo Pendiente");

        SaldoPendienteInput.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        SaldoPendienteInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SaldoPendienteInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaldoPendienteInputActionPerformed(evt);
            }
        });

        LblCantidadPagar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        LblCantidadPagar.setText("Cantidad a Pagar");

        CantidadPagarInput.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        CantidadPagarInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CantidadPagarInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadPagarInputActionPerformed(evt);
            }
        });

        saveBtnRealizarPagos.setBackground(new java.awt.Color(51, 204, 0));
        saveBtnRealizarPagos.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        saveBtnRealizarPagos.setForeground(new java.awt.Color(255, 255, 255));
        saveBtnRealizarPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        saveBtnRealizarPagos.setText("Guardar");
        saveBtnRealizarPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnRealizarPagosActionPerformed(evt);
            }
        });

        CancelBtn1.setBackground(new java.awt.Color(255, 0, 0));
        CancelBtn1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        CancelBtn1.setForeground(new java.awt.Color(255, 255, 255));
        CancelBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        CancelBtn1.setText("Cancelar");
        CancelBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(background1Layout.createSequentialGroup()
                                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LblCliente, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblSaldoPendiente, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SaldoPendienteInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                                    .addComponent(nombreClienteInput, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(88, 88, 88))
                            .addGroup(background1Layout.createSequentialGroup()
                                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CantidadPagarInput, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblCantidadPagar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(saveBtnRealizarPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CancelBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(LblCliente)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(nombreClienteInput, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LblSaldoPendiente, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaldoPendienteInput, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LblCantidadPagar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CantidadPagarInput, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CancelBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(saveBtnRealizarPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreClienteInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreClienteInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreClienteInputActionPerformed

    private void SaldoPendienteInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaldoPendienteInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaldoPendienteInputActionPerformed

    private void CantidadPagarInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadPagarInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadPagarInputActionPerformed

    private void saveBtnRealizarPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnRealizarPagosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveBtnRealizarPagosActionPerformed

    private void CancelBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                RealizarPago dialog = new RealizarPago(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn1;
    private javax.swing.JTextField CantidadPagarInput;
    private javax.swing.JLabel LblCantidadPagar;
    private javax.swing.JLabel LblCliente;
    private javax.swing.JLabel LblSaldoPendiente;
    private javax.swing.JTextField SaldoPendienteInput;
    private javax.swing.JPanel background1;
    private javax.swing.JPanel background3;
    private javax.swing.JPanel background4;
    private javax.swing.JPanel background5;
    private javax.swing.JPanel background6;
    private javax.swing.JPanel header;
    private javax.swing.JPanel header6;
    private javax.swing.JPanel header7;
    private javax.swing.JPanel header8;
    private javax.swing.JPanel header9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField nombreClienteInput;
    private javax.swing.JTextField nombrePeriodicidadInput2;
    private javax.swing.JTextField nombrePeriodicidadInput3;
    private javax.swing.JTextField nombrePeriodicidadInput4;
    private javax.swing.JTextField nombrePeriodicidadInput5;
    private javax.swing.JLabel nombrePeriodicidadLbl2;
    private javax.swing.JLabel nombrePeriodicidadLbl3;
    private javax.swing.JLabel nombrePeriodicidadLbl4;
    private javax.swing.JLabel nombrePeriodicidadLbl5;
    private javax.swing.JButton saveBtnRealizarPagos;
    private javax.swing.JLabel title6;
    private javax.swing.JLabel title7;
    private javax.swing.JLabel title8;
    private javax.swing.JLabel title9;
    private javax.swing.JLabel titleRealizarPagos;
    // End of variables declaration//GEN-END:variables
}
