/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.misproyectos.views.RegistrosDePagos;

import static com.misproyectos.views.MainWindow.ShowJPanel;
import javax.swing.SwingUtilities;
import java.awt.Window;
import java.awt.Frame;

/**
 *
 * @author IK
 */
public class Registrosdepagos extends javax.swing.JPanel {

    /**
     * Creates new form Registrosdepagos
     */
    public Registrosdepagos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new javax.swing.JPanel();
        headermodulopagos = new javax.swing.JPanel();
        title_modulopagos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        PrestamosPendientesTable = new javax.swing.JTable();
        IrPagarBtn = new javax.swing.JButton();
        PrestamosPendientes = new javax.swing.JPanel();
        titlePrestamosPendientes = new javax.swing.JLabel();
        textomodulopagos = new javax.swing.JLabel();
        TotalprestamosCard = new javax.swing.JPanel();
        LblTotalPrestamos = new javax.swing.JLabel();
        LblPrestamosActivos = new javax.swing.JLabel();
        LblNumTotalPrestamos = new javax.swing.JLabel();
        SaldototalCard = new javax.swing.JPanel();
        LblSaldoTotal = new javax.swing.JLabel();
        LblPendientedecobrar = new javax.swing.JLabel();
        Lblcantidadsaldo = new javax.swing.JLabel();

        background1.setBackground(new java.awt.Color(239, 239, 239));
        background1.setForeground(new java.awt.Color(255, 255, 255));

        headermodulopagos.setBackground(new java.awt.Color(0, 124, 239));

        title_modulopagos.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        title_modulopagos.setForeground(new java.awt.Color(255, 255, 255));
        title_modulopagos.setText("Modulo de Pagos");

        javax.swing.GroupLayout headermodulopagosLayout = new javax.swing.GroupLayout(headermodulopagos);
        headermodulopagos.setLayout(headermodulopagosLayout);
        headermodulopagosLayout.setHorizontalGroup(
            headermodulopagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headermodulopagosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title_modulopagos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headermodulopagosLayout.setVerticalGroup(
            headermodulopagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headermodulopagosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title_modulopagos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PrestamosPendientesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Importe", "Saldo Pendiente"
            }
        ));
        PrestamosPendientesTable.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(PrestamosPendientesTable);

        IrPagarBtn.setBackground(new java.awt.Color(51, 204, 0));
        IrPagarBtn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        IrPagarBtn.setForeground(new java.awt.Color(255, 255, 255));
        IrPagarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paymets.png"))); // NOI18N
        IrPagarBtn.setText("Ir a Pagar");
        IrPagarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrPagarBtnActionPerformed(evt);
            }
        });

        PrestamosPendientes.setBackground(new java.awt.Color(51, 51, 51));

        titlePrestamosPendientes.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        titlePrestamosPendientes.setForeground(new java.awt.Color(255, 255, 255));
        titlePrestamosPendientes.setText("Prestamos Pendientes");

        javax.swing.GroupLayout PrestamosPendientesLayout = new javax.swing.GroupLayout(PrestamosPendientes);
        PrestamosPendientes.setLayout(PrestamosPendientesLayout);
        PrestamosPendientesLayout.setHorizontalGroup(
            PrestamosPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrestamosPendientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlePrestamosPendientes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PrestamosPendientesLayout.setVerticalGroup(
            PrestamosPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrestamosPendientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlePrestamosPendientes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        textomodulopagos.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        textomodulopagos.setText("Gestiona los pagos de prestamos pendientes");

        TotalprestamosCard.setBackground(new java.awt.Color(107, 203, 119));
        TotalprestamosCard.setPreferredSize(new java.awt.Dimension(148, 0));

        LblTotalPrestamos.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        LblTotalPrestamos.setForeground(new java.awt.Color(255, 255, 255));
        LblTotalPrestamos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loans.png"))); // NOI18N
        LblTotalPrestamos.setText("Total Prestamos");

        LblPrestamosActivos.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        LblPrestamosActivos.setForeground(new java.awt.Color(255, 255, 255));
        LblPrestamosActivos.setText("Prestamos activos");

        LblNumTotalPrestamos.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        LblNumTotalPrestamos.setText("1");

        javax.swing.GroupLayout TotalprestamosCardLayout = new javax.swing.GroupLayout(TotalprestamosCard);
        TotalprestamosCard.setLayout(TotalprestamosCardLayout);
        TotalprestamosCardLayout.setHorizontalGroup(
            TotalprestamosCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalprestamosCardLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(TotalprestamosCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LblPrestamosActivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblTotalPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblNumTotalPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        TotalprestamosCardLayout.setVerticalGroup(
            TotalprestamosCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalprestamosCardLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(LblTotalPrestamos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblNumTotalPrestamos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblPrestamosActivos)
                .addGap(14, 14, 14))
        );

        SaldototalCard.setBackground(new java.awt.Color(107, 203, 119));
        SaldototalCard.setPreferredSize(new java.awt.Dimension(148, 0));

        LblSaldoTotal.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        LblSaldoTotal.setForeground(new java.awt.Color(255, 255, 255));
        LblSaldoTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loans.png"))); // NOI18N
        LblSaldoTotal.setText("Saldo Total");

        LblPendientedecobrar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        LblPendientedecobrar.setForeground(new java.awt.Color(255, 255, 255));
        LblPendientedecobrar.setText("Pendiente de cobro");

        Lblcantidadsaldo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Lblcantidadsaldo.setText("$  ");

        javax.swing.GroupLayout SaldototalCardLayout = new javax.swing.GroupLayout(SaldototalCard);
        SaldototalCard.setLayout(SaldototalCardLayout);
        SaldototalCardLayout.setHorizontalGroup(
            SaldototalCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaldototalCardLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(SaldototalCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LblPendientedecobrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblSaldoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lblcantidadsaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        SaldototalCardLayout.setVerticalGroup(
            SaldototalCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaldototalCardLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(LblSaldoTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lblcantidadsaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblPendientedecobrar)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addComponent(textomodulopagos)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(background1Layout.createSequentialGroup()
                                .addComponent(TotalprestamosCard, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                                .addGap(121, 121, 121)
                                .addComponent(SaldototalCard, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                            .addComponent(headermodulopagos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PrestamosPendientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                            .addGroup(background1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(IrPagarBtn)))
                        .addGap(14, 14, 14))))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headermodulopagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(textomodulopagos)
                .addGap(39, 39, 39)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TotalprestamosCard, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaldototalCard, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(PrestamosPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IrPagarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void IrPagarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrPagarBtnActionPerformed
    Window topWindow = SwingUtilities.getWindowAncestor(this);
    RealizarPago dialogoPago = new RealizarPago((Frame) topWindow, true);
    dialogoPago.setLocationRelativeTo(topWindow);  
    dialogoPago.setVisible(true);
    }//GEN-LAST:event_IrPagarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IrPagarBtn;
    private javax.swing.JLabel LblNumTotalPrestamos;
    private javax.swing.JLabel LblPendientedecobrar;
    private javax.swing.JLabel LblPrestamosActivos;
    private javax.swing.JLabel LblSaldoTotal;
    private javax.swing.JLabel LblTotalPrestamos;
    private javax.swing.JLabel Lblcantidadsaldo;
    private javax.swing.JPanel PrestamosPendientes;
    private javax.swing.JTable PrestamosPendientesTable;
    private javax.swing.JPanel SaldototalCard;
    private javax.swing.JPanel TotalprestamosCard;
    private javax.swing.JPanel background1;
    private javax.swing.JPanel headermodulopagos;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel textomodulopagos;
    private javax.swing.JLabel titlePrestamosPendientes;
    private javax.swing.JLabel title_modulopagos;
    // End of variables declaration//GEN-END:variables
}
