/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.misproyectos.views.login;

import com.misproyectos.controllers.LoginController;
import com.misproyectos.exceptions.ValidacionException;
import com.misproyectos.repositories.UsuarioRepository;

import javax.swing.*;

/**
 *
 * @author Fausto
 */
public class LoginDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginDialog.class.getName());

    /**
     * Creates new form LoginDialog
     */
    public LoginDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initListeners();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        usuarioLbl = new javax.swing.JLabel();
        usuarioInput = new javax.swing.JTextField();
        passwordLbl = new javax.swing.JLabel();
        passwordInput = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        registrateBtn = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoPrestamos.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 140, 150));

        usuarioLbl.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        usuarioLbl.setForeground(new java.awt.Color(255, 255, 255));
        usuarioLbl.setText("Nombre de usuario");
        jPanel1.add(usuarioLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));
        jPanel1.add(usuarioInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 260, 40));

        passwordLbl.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        passwordLbl.setForeground(new java.awt.Color(255, 255, 255));
        passwordLbl.setText("Contraseña");
        jPanel1.add(passwordLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));
        jPanel1.add(passwordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 260, 40));

        loginBtn.setBackground(new java.awt.Color(0, 124, 239));
        loginBtn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Iniciar Sesión");
        jPanel1.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 260, 40));

        registrateBtn.setBackground(new java.awt.Color(0, 124, 239));
        registrateBtn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        registrateBtn.setForeground(new java.awt.Color(255, 255, 255));
        registrateBtn.setText("Registrate");
        registrateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(registrateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 470, 100, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgroundLogin.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 527));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrateBtnActionPerformed
        RegistroDialog.showRegisterDialog();
        this.dispose();
    }//GEN-LAST:event_registrateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                LoginDialog dialog = new LoginDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void initListeners() {
        LoginController controller = new LoginController(
                this,
                new UsuarioRepository()
        );
        controller.initListeners();
    }

    public String getUsuario() {
        return usuarioInput.getText().trim();
    }

    public String getPassword() {
        return passwordInput.getText().trim();
    }

    public JButton iniciarSessionBtn() {
        return loginBtn;
    }

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField passwordInput;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JButton registrateBtn;
    private javax.swing.JTextField usuarioInput;
    private javax.swing.JLabel usuarioLbl;
    // End of variables declaration//GEN-END:variables
}
