/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.misproyectos.views.login;

import com.misproyectos.controllers.RegistroController;
import com.misproyectos.repositories.UsuarioRepository;

import javax.swing.*;

/**
 *
 * @author Fausto
 */
public class RegistroDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroDialog.class.getName());

    /**
     * Creates new form Registro
     */
    public RegistroDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        usuario_r_Lbl = new javax.swing.JLabel();
        passwordInput = new javax.swing.JTextField();
        correo_lbl = new javax.swing.JLabel();
        correoInput_r = new javax.swing.JTextField();
        password_r_Lbl = new javax.swing.JLabel();
        nombreUsuarioInput = new javax.swing.JTextField();
        registerBtn_r = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoPrestamos.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 140, 150));

        usuario_r_Lbl.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        usuario_r_Lbl.setForeground(new java.awt.Color(255, 255, 255));
        usuario_r_Lbl.setText("Nombre de usuario");
        jPanel1.add(usuario_r_Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));
        jPanel1.add(passwordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 260, 40));

        correo_lbl.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        correo_lbl.setForeground(new java.awt.Color(255, 255, 255));
        correo_lbl.setText("Correo");
        jPanel1.add(correo_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));
        jPanel1.add(correoInput_r, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 260, 40));

        password_r_Lbl.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        password_r_Lbl.setForeground(new java.awt.Color(255, 255, 255));
        password_r_Lbl.setText("Contraseña");
        jPanel1.add(password_r_Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));
        jPanel1.add(nombreUsuarioInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 260, 40));

        registerBtn_r.setBackground(new java.awt.Color(0, 124, 239));
        registerBtn_r.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        registerBtn_r.setForeground(new java.awt.Color(255, 255, 255));
        registerBtn_r.setText("Registrarse");
        jPanel1.add(registerBtn_r, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 260, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgroundLogin.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 527));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                RegistroDialog dialog = new RegistroDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public String getUsuario2() {
        return nombreUsuarioInput.getText().trim();
    }

    public String getPassword2() {
        return passwordInput.getText().trim();
    }

    public String getCorreo1() {
        return correoInput_r.getText().trim();
    }

    public JButton getRegisternBtn_r() {
        return registerBtn_r;
    }

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    public void initListeners(){
        RegistroController registroController = new RegistroController(
                this,
                new UsuarioRepository()
        );
        registroController.initListeners();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextField correoInput_r;
    private javax.swing.JLabel correo_lbl;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField nombreUsuarioInput;
    private javax.swing.JTextField passwordInput;
    private javax.swing.JLabel password_r_Lbl;
    private javax.swing.JButton registerBtn_r;
    private javax.swing.JLabel usuario_r_Lbl;
    // End of variables declaration//GEN-END:variables
}
