/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.misproyectos.views.periodicidades;

import com.misproyectos.models.Periodicidad;

import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Fausto
 */
public class EditPeriodicidadDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditPeriodicidadDialog.class.getName());

    /**
     * Creates new form EditPeriodicidadDialog
     */
    public EditPeriodicidadDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        background1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        nombrePeriodicidadLbl = new javax.swing.JLabel();
        nombrePeriodicidadInput = new javax.swing.JTextField();
        DiasPeriodicidadLbl = new javax.swing.JLabel();
        diasPeriodicidadInput = new javax.swing.JTextField();
        PorcentajeInteresesLbl = new javax.swing.JLabel();
        PorcentajeInteresesInput = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        background1.setBackground(new java.awt.Color(239, 239, 239));
        background1.setForeground(new java.awt.Color(255, 255, 255));

        header.setBackground(new java.awt.Color(0, 124, 239));

        title.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Editar Periodicidad");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
                headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(title)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
                headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(title)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));

        nombrePeriodicidadLbl.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        nombrePeriodicidadLbl.setText("Nombre de la Periodicidad*");

        nombrePeriodicidadInput.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        nombrePeriodicidadInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nombrePeriodicidadInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrePeriodicidadInputActionPerformed(evt);
            }
        });

        DiasPeriodicidadLbl.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        DiasPeriodicidadLbl.setText("Días de la Periodicidad*");

        diasPeriodicidadInput.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        diasPeriodicidadInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        diasPeriodicidadInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diasPeriodicidadInputActionPerformed(evt);
            }
        });

        PorcentajeInteresesLbl.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        PorcentajeInteresesLbl.setText("Porcentaje de Intereses*");

        PorcentajeInteresesInput.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        PorcentajeInteresesInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PorcentajeInteresesInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PorcentajeInteresesInputActionPerformed(evt);
            }
        });

        saveBtn.setBackground(new java.awt.Color(0, 124, 239));
        saveBtn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        saveBtn.setText("Guardar");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
                background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(background1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(background1Layout.createSequentialGroup()
                                                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(nombrePeriodicidadLbl, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(DiasPeriodicidadLbl, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(diasPeriodicidadInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                                                        .addComponent(nombrePeriodicidadInput, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGap(30, 30, 30)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(background1Layout.createSequentialGroup()
                                                                .addGap(28, 28, 28)
                                                                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(background1Layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(PorcentajeInteresesLbl))
                                                        .addGroup(background1Layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(PorcentajeInteresesInput, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(9, 9, 9))
        );
        background1Layout.setVerticalGroup(
                background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(background1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(background1Layout.createSequentialGroup()
                                                .addComponent(nombrePeriodicidadLbl)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(nombrePeriodicidadInput, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(DiasPeriodicidadLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(diasPeriodicidadInput, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, background1Layout.createSequentialGroup()
                                                        .addComponent(PorcentajeInteresesLbl)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(PorcentajeInteresesInput, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 701, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 251, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombrePeriodicidadInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrePeriodicidadInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrePeriodicidadInputActionPerformed

    private void diasPeriodicidadInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diasPeriodicidadInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diasPeriodicidadInputActionPerformed

    private void PorcentajeInteresesInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PorcentajeInteresesInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PorcentajeInteresesInputActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    //getters
    public String getNombre() {
        return nombrePeriodicidadInput.getText().trim();
    }

    public String getPorcentaje() {
        return PorcentajeInteresesInput.getText().trim();
    }

    public String getDiasPeriodicidad() {
        return diasPeriodicidadInput.getText().trim();
    }

    public JButton getSaveBtn() {
        return saveBtn;
    }

    //setter
    public void setPeriodicidadInputs(Periodicidad periodicidad) {
        nombrePeriodicidadInput.setText(periodicidad.getNombrePeriodicidad());
        diasPeriodicidadInput.setText(String.valueOf(periodicidad.getDiasPeriodicidad()));
        PorcentajeInteresesInput.setText(String.valueOf(periodicidad.getPorcentajeIntereses()));
    }

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DiasPeriodicidadLbl;
    private javax.swing.JTextField PorcentajeInteresesInput;
    private javax.swing.JLabel PorcentajeInteresesLbl;
    private javax.swing.JPanel background1;
    private javax.swing.JTextField diasPeriodicidadInput;
    private javax.swing.JPanel header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nombrePeriodicidadInput;
    private javax.swing.JLabel nombrePeriodicidadLbl;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
